# Generated by Django 5.1.7 on 2025-03-31 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_certificate_options_certificate_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
